Technobook.MVC/Areas/Profile/Models/Forms/SearchUserForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Technobook.MVC.Areas.Profile.Models.Forms
{
    public class SearchUserForm
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
    }
}

Technobook.MVC/Areas/Profile/Models/Forms/UpdateUserForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Technobook.MVC.Areas.Profile.Models.Forms
{
    public class UpdateUserForm
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [EmailAddress]
        public string Email { get; set; }
    }
}

Technobook.MVC/Models/Forms/LoginForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Technobook.MVC.Infrastructure.Forms
{
    public class LoginForm
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Technobook.MVC/Models/Forms/RegisterForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Technobook.MVC.Infrastructure.Forms
{
    public class RegisterForm
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Technobook.MVC/Areas/Profile/Controllers/RelationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Technobook.Model.Client.Models;
using Technobook.Model.Client.Services;
using Technobook.MVC.Infrastructure.Attributes;
using Technobook.MVC.Infrastructure.Session;

namespace Technobook.MVC.Areas.Profile.Controllers
{
    public class RelationController : Controller
    {
        // GET: Profile/Relation
        [AuthRequired]
        public ActionResult GetPendingRequestsCount()
        {
            ViewBag.Count = ClientServicesLocator.Instance.Users.GetPendingRequests(SessionManager.User.ID).Count().ToString();
            return PartialView();
        }

        public ActionResult AnswerRequest(int UserID, bool Answer)
        {
            ClientServicesLocator.Instance.Relations.AnswerFriendRequest(new Relation(UserID, SessionManager.User.ID, Answer));
            return RedirectToAction("GetFriendRequests", "User");
        }
    }
}

Technobook.MVC/Areas/Profile/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Technobook.Model.Client.Models;
using Technobook.Model.Client.Services;
using Technobook.MVC.Areas.Profile.Models.Forms;
using Technobook.MVC.Infrastructure.Attributes;
using Technobook.MVC.Infrastructure.Session;

namespace Technobook.MVC.Areas.Profile.Controllers
{
    [AuthRequired]
    public class UserController : Controller
    {
        // GET: Profile/User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UpdateProfile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdateProfile(UpdateUserForm form)
        {
            if (ModelState.IsValid)
            {
                User UpdatedUser = new User(
                        SessionManager.User.ID, 
                        form.FirstName ?? SessionManager.User.FirstName, 
                        form.LastName ?? SessionManager.User.LastName, 
                        form.Email ?? SessionManager.User.Email, ""
                    );

                User NewUser = ClientServicesLocator.Instance.Users.UpdateUser(UpdatedUser);

                if(NewUser != null)
                {
                    SessionManager.User = NewUser;
                }

                return RedirectToAction("Index");
            }
            return RedirectToAction("UpdateProfile");
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(SearchUserForm form)
        {
            if (ModelState.IsValid)
            {
               
                    return RedirectToAction("UsersList", new { FirstName = form.FirstName, LastName = form.LastName});
              
            }
            return View();
        }

        public ActionResult UsersList(string FirstName, string LastName)
        {
            IEnumerable<User> Users = ClientServicesLocator.Instance.Users.GetUsersByName(FirstName, LastName);
            List<User> users = new List<User>();

            if (Users != null)
            {
                foreach (User u in Users)
                    users.Add(u);
                return View("UsersList", users);
            }
            return View(users);
        }

        public ActionResult GetFriendRequests()
        {
            IEnumerable<User> requests = ClientServicesLocator.Instance.Users.GetPendingRequests(SessionManager.User.ID);
            List<User> users = new List<User>();
            if(requests != null)
            {
                foreach (User u in requests)
                {
                    users.Add(u);
                }
                return View(users);
            }
            return RedirectToAction("Index");
        }

        public ActionResult SendFriendRequest(int id)
        {
            try
            {
                ClientServicesLocator.Instance.Relations.SendFriendRequest(new Relation(SessionManager.User.ID, id));
                return RedirectToAction("Search");
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Technobook.MVC/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Technobook.Model.Client.Models;
using Technobook.Model.Client.Services;
using Technobook.MVC.Infrastructure.Forms;
using Technobook.MVC.Infrastructure.Session;

namespace Technobook.MVC.Controllers
{
    public class AuthController : Controller
    {
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterForm form)
        {
            if (ModelState.IsValid)
            {
                User u = new User(0, form.FirstName, form.LastName, form.Email, form.Password);
                if (ClientServicesLocator.Instance.Users.Register(u) != 0)
                {
                    return RedirectToAction("Login");
                }
            }

            return RedirectToAction("Index", "Home");
        }

        // GET: Auth
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginForm form)
        {
            if (ModelState.IsValid)
            {
                User u = new User(form.Email, form.Password);
                User res = ClientServicesLocator.Instance.Users.Login(u);
                if (res != null)
                {
                    SessionManager.User = res;
                    return RedirectToAction("Index", "User", new { area="Profile"});
                }
            }

            return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

Technobook.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Technobook.MVC.Infrastructure.Attributes;

namespace Technobook.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [AuthRequired]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Technobook.MVC/Areas/Profile/Views/Relation/GetPendingRequestsCount.cshtml
@{ 
    ViewBag.Title = "PendingRequestsCount";
}

@if(int.Parse(ViewBag.Count) > 0){
    <li>
        @Html.ActionLink((string)ViewBag.Count + (int.Parse(ViewBag.Count) > 1 ? " requests" : " request"), "GetFriendRequests", "User")
    </li>

}

Technobook.MVC/Areas/Profile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Technobook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Logout", "Logout", "Auth", new { area = "" }, null);
                    </li>
                    <li>
                        @Html.ActionLink("Search", "Search", "User")
                    </li>
                    @{Html.RenderAction("GetPendingRequestsCount", "Relation");}
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Technobook.MVC/Areas/Profile/Views/User/GetFriendRequests.cshtml
@model IEnumerable<Technobook.Model.Client.Models.User>

@{
    ViewBag.Title = "GetFriendRequests";
}

<h2>GetFriendRequests</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Accept", "AnswerRequest", "Relation", new { UserID = item.ID, Answer = true}, null)
        </td>
        <td>
            @Html.ActionLink("Refuse", "AnswerRequest", "Relation", new { UserID = item.ID, Answer = false }, null)
        </td>
    </tr>
}

</table>

Technobook.MVC/Areas/Profile/Views/User/Index.cshtml
@using Technobook.MVC.Infrastructure.Session

@{
    ViewBag.Title = "Index";
}

<h2>Hello @SessionManager.User.FirstName</h2>

Technobook.MVC/Areas/Profile/Views/User/Search.cshtml
@model Technobook.MVC.Areas.Profile.Models.Forms.SearchUserForm

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SearchUserForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Technobook.MVC/Areas/Profile/Views/User/UpdateProfile.cshtml
@model Technobook.MVC.Areas.Profile.Models.Forms.UpdateUserForm

@{
    ViewBag.Title = "UpdateProfile";
}

<h2>UpdateProfile</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UpdateUserForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Technobook.MVC/Areas/Profile/Views/User/UsersList.cshtml
@model IEnumerable<Technobook.Model.Client.Models.User>

@{
    ViewBag.Title = "UsersList";
}

<h2>UsersList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
      
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.ActionLink("Send Friend Request", "SendFriendRequest", "User", new { id = item.ID}, null)
        </td>
    </tr>
}

</table>

Technobook.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Technobook.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Technobook.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Technobook.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Technobook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Login", "Auth")</li>
                    <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>